=== OpenST/mosaic-chains/src/Config/GatewayConfig.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/GatewayConfig",
  "definitions": {
    "Address": {
      "type": "string",
      "pattern":"^0x[a-fA-F0-9]{40}$"
    },
    "OriginChainContractAddresses": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "baseTokenAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of base token contract on origin chain"
        },
        "valueTokenAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of value token contract on origin chain"
        },
        "gatewayOrganizationAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of ost gateway organization on origin chain"
        },
        "eip20GatewayAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of gateway contract on origin chain"
        },
        "merklePatriciaLibAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of merkle patricia library on origin chain"
        },
        "gatewayLibAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of gateway library on origin chain"
        },
        "messageBusAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of message bus library on origin chain"
        },
        "stakePoolAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of staker pool contract on origin chain."
        }
      },
      "required": [
        "baseTokenAddress",
        "valueTokenAddress",
        "gatewayOrganizationAddress",
        "eip20GatewayAddress"
      ],
      "title": "OriginChainContractAddresses",
      "description": "Contract addresses on origin chain"
    },
    "AuxiliaryChainContractAddresses": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "coGatewayOrganizationAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of ost cogateway organization on auxiliary chain"
        },
        "eip20CoGatewayAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of cogateway contract on auxiliary chain"
        },
        "utilityTokenAddress": {
          "$ref": "#/definitions/Address",
          "description": "Utility token contract address"
        },
        "merklePatriciaLibAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of merkle patricia library on auxiliary chain"
        },
        "gatewayLibAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of gateway library on auxiliary chain"
        },
        "messageBusAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of message bus library on auxiliary chain"
        },
        "redeemPoolAddress": {
          "$ref": "#/definitions/Address",
          "description": "Address of redeem pool contract on auxiliary chain"
        }
      },
      "required": [
        "coGatewayOrganizationAddress",
        "eip20CoGatewayAddress",
        "utilityTokenAddress"
      ],
      "title": "Auxiliary",
      "description": "Contract addresses of auxiliary chain"
    },
    "GatewayConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "mosaicConfigFilePath": {
          "type": "string",
          "description": "File path of mosaic config."
        },
        "auxChainId": {
          "type": "integer",
          "description": "auxiliary chain id as integer"
        },
        "originContracts": {
          "$ref": "#/definitions/OriginChainContractAddresses",
          "description": "Origin chain contract addresses."
        },
        "auxiliaryContracts": {
          "$ref": "#/definitions/AuxiliaryChainContractAddresses",
          "description": "Auxiliary chain contract addresses."
        }
      },
      "required": [
        "mosaicConfigFilePath",
        "auxChainId",
        "originContracts",
        "auxiliaryContracts"
      ],
      "title": "GatewayConfig",
      "description": "This object represents GatewayConfig of single gateway pair."
    }
  }
}

=== OpenST/mosaic-chains/tests/Config/testdata/0xae02c7b1c324a8d94a564bc8d713df89eae441fe.json
{
  "mosaicConfigFilePath":"./tests/Config/testdata/mosaic.json",
  "auxChainId":1000,
  "originContracts":{
    "baseTokenAddress":"0x9ac77f4c0ca4d0f2142d7a77175cf4f1295fb2d8",
    "valueTokenAddress":"0x8e183Fd2cd55C7C05bBf4FAC989740f69e559A6d",
    "gatewayOrganizationAddress":"0x3f99f42d226A0CD1C1Fcae1e8dC11b2f7a9DcE4B",
    "eip20GatewayAddress":"0xaE02C7b1C324A8D94A564bC8d713Df89eae441fe"
  },
  "auxiliaryContracts":{
    "coGatewayOrganizationAddress":"0x2D586C7E220839a9284888B10aDF4823AcD6EdF3",
    "utilityTokenAddress":"0x62F8729C1C282C231a22252e90CE9735533D2518",
    "eip20CoGatewayAddress":"0xc6fF898ceBf631eFb58eEc7187E4c1f70AE8d943"
  }
}

=== OpenST/mosaic-chains/chains/goerli/1405/gateway-0x6649c6FF3629aE875b91B6C1551139c9feaA2514/gateway-config.json
{
  "mosaicConfigFilePath":"~/.mosaic/goerli/mosaic.json",
  "auxChainId":1405,
  "originContracts":{
    "baseTokenAddress":"0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
    "valueTokenAddress":"0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
    "gatewayOrganizationAddress":"0x77DDDB66b12b2279A83D61fF443F1d8D16352C59",
    "eip20GatewayAddress":"0x6649c6FF3629aE875b91B6C1551139c9feaA2514",
    "gatewayLibAddress":"0x0f08341505C01b7bc05C95A99aB7427eD4C3195F",
    "messageBusAddress":"0xcaB4728ea030A04A183928884a6dcD83857d96Ba",
    "merklePatriciaLibAddress":"0x83aA52516805Ff323CA1033a12c6bF133d9AC17e"
  },
  "auxiliaryContracts":{
    "coGatewayOrganizationAddress":"0x47Ef953C4372457754d3471Ca2BB1b5d6AD8F245",
    "eip20CoGatewayAddress":"0x962e1404D6957d8fF56F8fE79a3fC2B670C3d578",
    "utilityTokenAddress":"0xBB5676d85d28DA039F982C07E4217fB0FDB2c2ef",
    "gatewayLibAddress":"0xa718f65c96a177d8967E8f6D67A7872b26771495",
    "messageBusAddress":"0x8F3578462BaF62e48Ad02820f4b7cd9788B200B6",
    "merklePatriciaLibAddress":"0x4473FBF3390e49e79b27D229b9BF230DAD78414e"
  }
}
